import os

SECRET_KEY = os.environ['SECRET_KEY']
RDS_DATABASE_HOST = os.environ['RDS_DATABASE_HOST']
RDS_DATABASE_USER = os.environ['RDS_DATABASE_USER']
RDS_DATABASE_PASSWORD = os.environ['RDS_DATABASE_PASSWORD']
RDS_DATABASE_NAME = os.environ['RDS_DATABASE_NAME']
RDS_PORT = os.environ['RDS_PORT']

AMEYO_DATABASE_HOST = os.environ['AMEYO_DATABASE_HOST']
AMEYO_DATABASE_USER = os.environ['AMEYO_DATABASE_USER']
AMEYO_DATABASE_PASSWORD = os.environ['AMEYO_DATABASE_PASSWORD']
AMEYO_PORT = os.environ['AMEYO_PORT']
